# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TacPac' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TacPac

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'IQKeyboardManagerSwift'
pod 'MaterialTextField', '~> 0.2'
pod 'NMessenger'

  target 'TacPacTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TacPacUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'SwiftKeychainWrapper'

pod 'NVActivityIndicatorView'

end
